### ISSUE TITLE
Support lua 5.3

### ISSUE THREAD

**Issue by daurnimator** [pllua/pllua-deprecated#20]
Work with lua 5.3

Major new feature is integer support, this means the `lua_int64` code can be dropped.

Currently these issues are present:

```
plluaspi.c: In function ‘luaP_cursorfetch’:
plluaspi.c:738:34: warning: implicit declaration of function ‘luaL_optlong’ [-Wimplicit-function-declaration]
   SPI_cursor_fetch(c->cursor, 1, luaL_optlong(L, 2, FETCH_ALL));
                                  ^
pllua_errors.c: In function ‘luaB_error’:
pllua_errors.c:16:17: warning: implicit declaration of function ‘luaL_optint’ [-Wimplicit-function-declaration]
     int level = luaL_optint(L, 2, 1);
                 ^
```

These should be easily solved by changing to `luaL_optinteger`

**Comment by mbalmer** [comment]
I changed these calls to luaL_optineger, PL/Lua should now work just fine on 5.3.  The int64 stuff need inspection, though.
